<a href="https://colab.research.google.com/github/IsfaquethedataAnalyst/Dataanalysis/blob/main/Enhancing_Hospital_Efficiency_with_ML_Data_Cleaning%2C_XGBoost%2C_and_Predictive_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
train = pd.read_csv('train.csv')
train

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,0-10
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,41-50
2,3,10,e,1,X,2,anesthesia,S,E,2.0,31397,7.0,Trauma,Extreme,2,51-60,4745.0,31-40
3,4,26,b,2,Y,2,radiotherapy,R,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,7272.0,41-50
4,5,26,b,2,Y,2,radiotherapy,S,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,5558.0,41-50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,19,a,7,Y,2,gynecology,S,C,2.0,104970,8.0,Emergency,Minor,2,11-20,4894.0,0-10
4996,4997,26,b,2,Y,2,gynecology,Q,D,4.0,104970,8.0,Trauma,Minor,2,11-20,6987.0,31-40
4997,4998,32,f,9,Y,3,gynecology,S,B,2.0,68447,5.0,Emergency,Moderate,4,41-50,4196.0,51-60
4998,4999,26,b,2,Y,3,gynecology,R,D,2.0,68447,5.0,Trauma,Moderate,3,41-50,4560.0,21-30
4999,5000,9,d,5,Z,4,anesthesia,R,F,4.0,68447,5.0,Trauma,Moderate,2,41-50,6315.0,11-20

In [54]:
train.info()
train.Stay.unique()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   case_id                            0 non-null      int64
 1   Hospital_code                      0 non-null      int64
 2   Hospital_type_code                 0 non-null      int64
 3   City_Code_Hospital                 0 non-null      int64
 4   Hospital_region_code               0 non-null      int64
 5   Available Extra Rooms in Hospital  0 non-null      int64
 6   Department                         0 non-null      int64
 7   Ward_Type                          0 non-null      int64
 8   Ward_Facility_Code                 0 non-null      int64
 9   Bed Grade                          0 non-null      float64
 10  patientid                          0 non-null      int64
 11  City_Code_Patient                  0 non-null      float64
 12  Type of Admission                  0 non-null      int64
 13  Severity of Illness                0 non-null      int64
 14  Visitors with Patient              0 non-null      int64
 15  Age                                0 non-null      int64
 16  Admission_Deposit                  0 non-null      float64
 17  Stay                               0 non-null      int64
dtypes: float64(3), int64(15)
memory usage: 0.0 bytes

array([], dtype=int64)

In [55]:
# NA values in train dataset
train.isnull().sum().sort_values(ascending = False)

case_id                              0.0
Hospital_code                        0.0
Admission_Deposit                    0.0
Age                                  0.0
Visitors with Patient                0.0
Severity of Illness                  0.0
Type of Admission                    0.0
City_Code_Patient                    0.0
patientid                            0.0
Bed Grade                            0.0
Ward_Facility_Code                   0.0
Ward_Type                            0.0
Department                           0.0
Available Extra Rooms in Hospital    0.0
Hospital_region_code                 0.0
City_Code_Hospital                   0.0
Hospital_type_code                   0.0
Stay                                 0.0
dtype: float64

In [2]:
test= pd.read_csv("test.csv")
test

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit
0,318439,21,c,3,Z,3,gynecology,S,A,2.0,17006,2.0,Emergency,Moderate,2,71-80,3095.0
1,318440,29,a,4,X,2,gynecology,S,F,2.0,17006,2.0,Trauma,Moderate,4,71-80,4018.0
2,318441,26,b,2,Y,3,gynecology,Q,D,4.0,17006,2.0,Emergency,Moderate,3,71-80,4492.0
3,318442,6,a,6,X,3,gynecology,Q,F,2.0,17006,2.0,Trauma,Moderate,3,71-80,4173.0
4,318443,28,b,11,X,2,gynecology,R,F,2.0,17006,2.0,Trauma,Moderate,4,71-80,4161.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,320434,26,b,2,Y,1,anesthesia,R,D,2.0,19303,8.0,Trauma,Extreme,4,51-60,8829.0
1996,320435,26,b,2,Y,4,gynecology,R,D,1.0,19303,8.0,Trauma,Extreme,6,51-60,3507.0
1997,320436,23,a,6,X,3,gynecology,Q,F,1.0,19303,8.0,Trauma,Extreme,3,51-60,4109.0
1998,320437,25,e,1,X,4,gynecology,Q,E,3.0,19303,8.0,Emergency,Extreme,4,51-60,4155.0
1999,320438,10,e,1,X,4,gynecology,Q,E,2.0,19303,8.0,Emergency,Extreme,3,51-60,4161.0

In [57]:
# NA values in test dataset
test.isnull().sum().sort_values(ascending = False)

case_id                              0.0
Hospital_code                        0.0
Admission_Deposit                    0.0
Age                                  0.0
Visitors with Patient                0.0
Severity of Illness                  0.0
Type of Admission                    0.0
City_Code_Patient                    0.0
patientid                            0.0
Bed Grade                            0.0
Ward_Facility_Code                   0.0
Ward_Type                            0.0
Department                           0.0
Available Extra Rooms in Hospital    0.0
Hospital_region_code                 0.0
City_Code_Hospital                   0.0
Hospital_type_code                   0.0
Stay                                 0.0
dtype: float64

In [58]:
# Number of distinct observations in train dataset
for i in train.columns:
    print(i, ':', train[i].nunique())

case_id : 0
Hospital_code : 0
Hospital_type_code : 0
City_Code_Hospital : 0
Hospital_region_code : 0
Available Extra Rooms in Hospital : 0
Department : 0
Ward_Type : 0
Ward_Facility_Code : 0
Bed Grade : 0
patientid : 0
City_Code_Patient : 0
Type of Admission : 0
Severity of Illness : 0
Visitors with Patient : 0
Age : 0
Admission_Deposit : 0
Stay : 0

In [59]:
# Number of distinct observations in test dataset
for i in test.columns:
    print(i, ':', test[i].nunique())

case_id : 0
Hospital_code : 0
Hospital_type_code : 0
City_Code_Hospital : 0
Hospital_region_code : 0
Available Extra Rooms in Hospital : 0
Department : 0
Ward_Type : 0
Ward_Facility_Code : 0
Bed Grade : 0
patientid : 0
City_Code_Patient : 0
Type of Admission : 0
Severity of Illness : 0
Visitors with Patient : 0
Age : 0
Admission_Deposit : 0
Stay : 0

In [9]:
# Replace missing values with the mode
train['Bed Grade'].fillna(train['Bed Grade'].mode()[0], inplace=True)
train['City_Code_Patient'].fillna(train['City_Code_Patient'].mode()[0], inplace=True)

# Print the DataFrame
print(train)

      case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0           1              8                  c                   3
1           2              2                  c                   5
2           3             10                  e                   1
3           4             26                  b                   2
4           5             26                  b                   2
...       ...            ...                ...                 ...
4995     4996             19                  a                   7
4996     4997             26                  b                   2
4997     4998             32                  f                   9
4998     4999             26                  b                   2
4999     5000              9                  d                   5

     Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                       Z                                  3  radiotherapy
1                       Z                                  2  radiotherapy
2                       X                                  2    anesthesia
3                       Y                                  2  radiotherapy
4                       Y                                  2  radiotherapy
...                   ...                                ...           ...
4995                    Y                                  2    gynecology
4996                    Y                                  2    gynecology
4997                    Y                                  3    gynecology
4998                    Y                                  3    gynecology
4999                    Z                                  4    anesthesia

     Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0            R                  F        2.0      31397                7.0
1            S                  F        2.0      31397                7.0
2            S                  E        2.0      31397                7.0
3            R                  D        2.0      31397                7.0
4            S                  D        2.0      31397                7.0
...        ...                ...        ...        ...                ...
4995         S                  C        2.0     104970                8.0
4996         Q                  D        4.0     104970                8.0
4997         S                  B        2.0      68447                5.0
4998         R                  D        2.0      68447                5.0
4999         R                  F        4.0      68447                5.0

     Type of Admission Severity of Illness  Visitors with Patient    Age  \
0            Emergency             Extreme                      2  51-60
1               Trauma             Extreme                      2  51-60
2               Trauma             Extreme                      2  51-60
3               Trauma             Extreme                      2  51-60
4               Trauma             Extreme                      2  51-60
...                ...                 ...                    ...    ...
4995         Emergency               Minor                      2  11-20
4996            Trauma               Minor                      2  11-20
4997         Emergency            Moderate                      4  41-50
4998            Trauma            Moderate                      3  41-50
4999            Trauma            Moderate                      2  41-50

      Admission_Deposit   Stay
0                4911.0   0-10
1                5954.0  41-50
2                4745.0  31-40
3                7272.0  41-50
4                5558.0  41-50
...                 ...    ...
4995             4894.0   0-10
4996             6987.0  31-40
4997             4196.0  51-60
4998             4560.0  21-30
4999             6315.0  11-20

[5000 rows x 18 columns]

In [10]:
# Replace missing values with the mode
test['Bed Grade'].fillna(test['Bed Grade'].mode()[0], inplace=True)
test['City_Code_Patient'].fillna(test['City_Code_Patient'].mode()[0], inplace=True)

# Print the DataFrame
print(test)

      case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0      318439             21                  c                   3
1      318440             29                  a                   4
2      318441             26                  b                   2
3      318442              6                  a                   6
4      318443             28                  b                  11
...       ...            ...                ...                 ...
1995   320434             26                  b                   2
1996   320435             26                  b                   2
1997   320436             23                  a                   6
1998   320437             25                  e                   1
1999   320438             10                  e                   1

     Hospital_region_code  Available Extra Rooms in Hospital  Department  \
0                       Z                                  3  gynecology
1                       X                                  2  gynecology
2                       Y                                  3  gynecology
3                       X                                  3  gynecology
4                       X                                  2  gynecology
...                   ...                                ...         ...
1995                    Y                                  1  anesthesia
1996                    Y                                  4  gynecology
1997                    X                                  3  gynecology
1998                    X                                  4  gynecology
1999                    X                                  4  gynecology

     Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0            S                  A        2.0      17006                2.0
1            S                  F        2.0      17006                2.0
2            Q                  D        4.0      17006                2.0
3            Q                  F        2.0      17006                2.0
4            R                  F        2.0      17006                2.0
...        ...                ...        ...        ...                ...
1995         R                  D        2.0      19303                8.0
1996         R                  D        1.0      19303                8.0
1997         Q                  F        1.0      19303                8.0
1998         Q                  E        3.0      19303                8.0
1999         Q                  E        2.0      19303                8.0

     Type of Admission Severity of Illness  Visitors with Patient    Age  \
0            Emergency            Moderate                      2  71-80
1               Trauma            Moderate                      4  71-80
2            Emergency            Moderate                      3  71-80
3               Trauma            Moderate                      3  71-80
4               Trauma            Moderate                      4  71-80
...                ...                 ...                    ...    ...
1995            Trauma             Extreme                      4  51-60
1996            Trauma             Extreme                      6  51-60
1997            Trauma             Extreme                      3  51-60
1998         Emergency             Extreme                      4  51-60
1999         Emergency             Extreme                      3  51-60

      Admission_Deposit
0                3095.0
1                4018.0
2                4492.0
3                4173.0
4                4161.0
...                 ...
1995             8829.0
1996             3507.0
1997             4109.0
1998             4155.0
1999             4161.0

[2000 rows x 17 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
le = LabelEncoder()

# Encode the 'Stay' column
train['Stay'] = le.fit_transform(train['Stay'].astype('str'))

# Print the encoded values
print(train['Stay'].unique())

[ 0  4  3  1  5  2  7 10  8  6  9]

In [17]:
# Set default value -1 for 'Stay' in 'test' DataFrame
train['Stay'] = -1

# Print the DataFrame
print(train)

      case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0           1              8                  c                   3
1           2              2                  c                   5
2           3             10                  e                   1
3           4             26                  b                   2
4           5             26                  b                   2
...       ...            ...                ...                 ...
4995     4996             19                  a                   7
4996     4997             26                  b                   2
4997     4998             32                  f                   9
4998     4999             26                  b                   2
4999     5000              9                  d                   5

     Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                       Z                                  3  radiotherapy
1                       Z                                  2  radiotherapy
2                       X                                  2    anesthesia
3                       Y                                  2  radiotherapy
4                       Y                                  2  radiotherapy
...                   ...                                ...           ...
4995                    Y                                  2    gynecology
4996                    Y                                  2    gynecology
4997                    Y                                  3    gynecology
4998                    Y                                  3    gynecology
4999                    Z                                  4    anesthesia

     Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0            R                  F        2.0      31397                7.0
1            S                  F        2.0      31397                7.0
2            S                  E        2.0      31397                7.0
3            R                  D        2.0      31397                7.0
4            S                  D        2.0      31397                7.0
...        ...                ...        ...        ...                ...
4995         S                  C        2.0     104970                8.0
4996         Q                  D        4.0     104970                8.0
4997         S                  B        2.0      68447                5.0
4998         R                  D        2.0      68447                5.0
4999         R                  F        4.0      68447                5.0

     Type of Admission Severity of Illness  Visitors with Patient    Age  \
0            Emergency             Extreme                      2  51-60
1               Trauma             Extreme                      2  51-60
2               Trauma             Extreme                      2  51-60
3               Trauma             Extreme                      2  51-60
4               Trauma             Extreme                      2  51-60
...                ...                 ...                    ...    ...
4995         Emergency               Minor                      2  11-20
4996            Trauma               Minor                      2  11-20
4997         Emergency            Moderate                      4  41-50
4998            Trauma            Moderate                      3  41-50
4999            Trauma            Moderate                      2  41-50

      Admission_Deposit  Stay
0                4911.0    -1
1                5954.0    -1
2                4745.0    -1
3                7272.0    -1
4                5558.0    -1
...                 ...   ...
4995             4894.0    -1
4996             6987.0    -1
4997             4196.0    -1
4998             4560.0    -1
4999             6315.0    -1

[5000 rows x 18 columns]

In [27]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Define the list of categorical columns
categorical_columns = ['Hospital_type_code', 'Hospital_region_code', 'Department', 'Ward_Type',
                       'Ward_Facility_Code', 'Type of Admission', 'Severity of Illness', 'Age']

# Iterate through each column
for col in categorical_columns:
    # Create a new LabelEncoder instance
    le = LabelEncoder()

    # Fit the LabelEncoder to the data in the current column
    le.fit(train[col])

    # Transform the data in the current column using the fitted LabelEncoder
    train[col] = le.transform(train[col])

In [29]:
# Filter data where Stay != -1
train = train[train['Stay'] != -1]

# Print the shape of the filtered DataFrame
print(train.shape)

(0, 18)

In [31]:
df = pd.read_csv("train.csv")

In [32]:
df

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,0-10
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,41-50
2,3,10,e,1,X,2,anesthesia,S,E,2.0,31397,7.0,Trauma,Extreme,2,51-60,4745.0,31-40
3,4,26,b,2,Y,2,radiotherapy,R,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,7272.0,41-50
4,5,26,b,2,Y,2,radiotherapy,S,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,5558.0,41-50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,19,a,7,Y,2,gynecology,S,C,2.0,104970,8.0,Emergency,Minor,2,11-20,4894.0,0-10
4996,4997,26,b,2,Y,2,gynecology,Q,D,4.0,104970,8.0,Trauma,Minor,2,11-20,6987.0,31-40
4997,4998,32,f,9,Y,3,gynecology,S,B,2.0,68447,5.0,Emergency,Moderate,4,41-50,4196.0,51-60
4998,4999,26,b,2,Y,3,gynecology,R,D,2.0,68447,5.0,Trauma,Moderate,3,41-50,4560.0,21-30
4999,5000,9,d,5,Z,4,anesthesia,R,F,4.0,68447,5.0,Trauma,Moderate,2,41-50,6315.0,11-20

In [33]:
# Filter the DataFrame based on the condition
train = df[df['Stay'] == -1]

In [36]:
df1 = pd.read_csv("test.csv")

In [37]:
df1

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit
0,318439,21,c,3,Z,3,gynecology,S,A,2.0,17006,2.0,Emergency,Moderate,2,71-80,3095.0
1,318440,29,a,4,X,2,gynecology,S,F,2.0,17006,2.0,Trauma,Moderate,4,71-80,4018.0
2,318441,26,b,2,Y,3,gynecology,Q,D,4.0,17006,2.0,Emergency,Moderate,3,71-80,4492.0
3,318442,6,a,6,X,3,gynecology,Q,F,2.0,17006,2.0,Trauma,Moderate,3,71-80,4173.0
4,318443,28,b,11,X,2,gynecology,R,F,2.0,17006,2.0,Trauma,Moderate,4,71-80,4161.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,320434,26,b,2,Y,1,anesthesia,R,D,2.0,19303,8.0,Trauma,Extreme,4,51-60,8829.0
1996,320435,26,b,2,Y,4,gynecology,R,D,1.0,19303,8.0,Trauma,Extreme,6,51-60,3507.0
1997,320436,23,a,6,X,3,gynecology,Q,F,1.0,19303,8.0,Trauma,Extreme,3,51-60,4109.0
1998,320437,25,e,1,X,4,gynecology,Q,E,3.0,19303,8.0,Emergency,Extreme,4,51-60,4155.0
1999,320438,10,e,1,X,4,gynecology,Q,E,2.0,19303,8.0,Emergency,Extreme,3,51-60,4161.0

In [38]:
# Filter the DataFrame based on the condition
test = df1[df1['Stay'] == -1]

In [39]:
print(df1.shape)

(2000, 17)

In [40]:
# Specify the columns to be removed
columns_to_remove = ['Stay', 'patientid', 'Hospital_region_code', 'Ward_Facility_Code']

# Create a new DataFrame 'test1' by dropping the specified columns
test1 = test.drop(columns=columns_to_remove, axis=1)

# Now, 'test1' is a modified version of 'test' with the specified columns removed

In [45]:
print(test1.shape)

(0, 14)

In [42]:
# Specify the columns to be removed
columns_to_remove_train = ['case_id', 'patientid', 'Hospital_region_code', 'Ward_Facility_Code']

# Create a new DataFrame 'train1' by dropping the specified columns
train1 = train.drop(columns=columns_to_remove_train, axis=1)

In [44]:
print(train1.shape)

(0, 14)

In [61]:
# Label Encoding Stay column in train dataset
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train['Stay'] = le.fit_transform(train['Stay'].astype('str'))

In [62]:
train.head()

Empty DataFrame
Columns: [case_id, Hospital_code, Hospital_type_code, City_Code_Hospital, Hospital_region_code, Available Extra Rooms in Hospital, Department, Ward_Type, Ward_Facility_Code, Bed Grade, patientid, City_Code_Patient, Type of Admission, Severity of Illness, Visitors with Patient, Age, Admission_Deposit, Stay]
Index: []

In [63]:
#Imputing dummy Stay column in test datset to concatenate with train dataset
test['Stay'] = -1
df = pd.concat([train, test])
df.shape

(0, 18)

In [64]:
#Label Encoding all the columns in Train and test datasets
for i in ['Hospital_type_code', 'Hospital_region_code', 'Department',
          'Ward_Type', 'Ward_Facility_Code', 'Type of Admission', 'Severity of Illness', 'Age']:
    le = LabelEncoder()
    df[i] = le.fit_transform(df[i].astype(str))

In [65]:
#Spearating Train and Test Datasets
train = df[df['Stay']!=-1]
test = df[df['Stay']==-1]

Feature **Engineering**

In [68]:
import numpy as np

def get_countid_enocde(train, test, cols, name):
  temp = train.groupby(cols)['case_id'].count().reset_index().rename(columns = {'case_id': name})
  temp2 = test.groupby(cols)['case_id'].count().reset_index().rename(columns = {'case_id': name})
  train = pd.merge(train, temp, how='left', on= cols)
  test = pd.merge(test,temp2, how='left', on= cols)
  train[name] = train[name].astype('float')
  test[name] = test[name].astype('float')
  train[name].fillna(np.median(temp[name]), inplace = True)
  test[name].fillna(np.median(temp2[name]), inplace = True)
  return train, test

In [69]:
train, test = get_countid_enocde(train, test, ['patientid'], name = 'count_id_patient')
train, test = get_countid_enocde(train, test,
                                 ['patientid', 'Hospital_region_code'], name = 'count_id_patient_hospitalCode')
train, test = get_countid_enocde(train, test,
                                 ['patientid', 'Ward_Facility_Code'], name = 'count_id_patient_wardfacilityCode')

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [71]:
# Droping duplicate columns
test1 = test.drop(['Stay', 'patientid', 'Hospital_region_code', 'Ward_Facility_Code'], axis =1)
train1 = train.drop(['case_id', 'patientid', 'Hospital_region_code', 'Ward_Facility_Code'], axis =1)

In [73]:
# Assuming 'train1' is your DataFrame with columns modified as per the previous steps

# Create feature and target variables
X1 = train1.drop('Stay', axis=1)  # Feature variables (excluding 'Stay' column)
y1 = train1['Stay']  # Target variable

# Check if the dataset is large enough for the specified split
if len(X1) >= 2:
    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.2, random_state=100)

    # Continue with the rest of your code for Naive Bayes and XGBoost

    # For Naive Bayes, you can use GaussianNB as an example
    from sklearn.naive_bayes import GaussianNB
    classifier_nb = GaussianNB()
    model_nb = classifier_nb.fit(X_train, y_train)
    prediction_nb = model_nb.predict(X_test)

    # Calculate the accuracy of the Naive Bayes model
    acc_score_nb = accuracy_score(y_test, prediction_nb)
    acc_score_nb = round(acc_score_nb, 2)
    print(f"Naive Bayes Model Accuracy: {acc_score_nb}")

    # For XGBoost, you can use the XGBoost code from the previous responses

else:
    print("Not enough samples in the dataset for the specified split.")

Not enough samples in the dataset for the specified split.

***Models***
Naive *Bayes* **Model**

In [75]:
# Assuming 'train1' is your DataFrame with columns modified as per the previous steps

# Create feature and target variables
X1 = train1.drop('Stay', axis=1)  # Feature variables (excluding 'Stay' column)
y1 = train1['Stay']  # Target variable

# Check if the dataset is large enough for the specified split
if len(X1) >= 2:
    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.2, random_state=100)

    # Naive Bayes
    from sklearn.naive_bayes import GaussianNB
    target_nb = y_train.values
    features_nb = X_train.values
    classifier_nb = GaussianNB()
    model_nb = classifier_nb.fit(features_nb, target_nb)
    prediction_nb = model_nb.predict(X_test)

    # Calculate the accuracy of the Naive Bayes model
    acc_score_nb = accuracy_score(prediction_nb, y_test)
    print("Naive Bayes Model Accuracy:", acc_score_nb * 100)

    # Continue with the rest of your code for XGBoost if needed

else:
    print("Not enough samples in the dataset for the specified split.")

Not enough samples in the dataset for the specified split.